### ISSUE TITLE
Design Patterns: read one execute one pattern in javascript in a day

### ISSUE THREAD

**Issue by ArtemTsevukh** [ArtemTsevukh/growth#17]
Reference: https://refactoring.guru/design-patterns

Acceptance Criteria:

* Have a design patterns folder in a growth project in some sort of notes folder
* Be able to execute each pattern for each pattern with node or in browser and so u will have them ready for further updates and modifications through the career

**Comment by conmute** [comment]
Add strategy pls
https://refactoring.guru/design-patterns/strategy/typescript/example#example-0
