### ISSUE TITLE
Know the PWA capabilities

### ISSUE THREAD

**Issue by ArtemTsevukh** [ArtemTsevukh/growth#3]
AC:

After running https://www.pwabuilder.com/reportcard?site=https://webboard.app and waiting stats to load, try to understand what is what in the report

Notes:

* Things to read for a starter https://web.dev/explore/progressive-web-apps

![Image](https://github.com/ArtemTsevukh/growth/assets/938118/11186430-93fd-41ed-857f-1daff55b58c1)

**Comment by conmute** [comment]
https://vite-pwa-org.netlify.app/

workbox-strategy / workbox-*

https://github.com/GoogleChrome/workbox
https://web.dev/learn/pwa/workbox
